// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwMRyguA7r5lizXZ4lqUT63dxCZqieNu8',
    appId: '1:1030506552773:web:67b903c229f931c6bbffac',
    messagingSenderId: '1030506552773',
    projectId: 'socialmedia-12c74',
    authDomain: 'socialmedia-12c74.firebaseapp.com',
    storageBucket: 'socialmedia-12c74.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCJDL2TwMY37rusU2Y4VR2Us9w_tyG4_c',
    appId: '1:1030506552773:android:a93097c1e1422712bbffac',
    messagingSenderId: '1030506552773',
    projectId: 'socialmedia-12c74',
    storageBucket: 'socialmedia-12c74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5t37xDC2TkbmiHCABi0XgT0u6IJZAIkw',
    appId: '1:1030506552773:ios:7935350f3e972c4abbffac',
    messagingSenderId: '1030506552773',
    projectId: 'socialmedia-12c74',
    storageBucket: 'socialmedia-12c74.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5t37xDC2TkbmiHCABi0XgT0u6IJZAIkw',
    appId: '1:1030506552773:ios:86ecaba2d09ac709bbffac',
    messagingSenderId: '1030506552773',
    projectId: 'socialmedia-12c74',
    storageBucket: 'socialmedia-12c74.appspot.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
